version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  tests:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: GATSBY_TARGET_ENV=$CIRCLE_BRANCH npm run deploy
workflows:
  stack:
    jobs:
      - tests
      - deploy:
          context: AWS Access Key
          requires:
            - tests
          filters:
            branches:
              only:
                - master
